package com.kolammaster.app

internal data class ContactCountryCallingCode(
    val countryName: String,
    val countryCode: String,
    val callingCode: String
)

internal fun ContactCountryCallingCode.flagEmoji(): String =
    countryCode
        .takeIf { it.length == 2 && it.all(Char::isLetter) }
        ?.uppercase()
        ?.map { character ->
            String(Character.toChars(0x1F1E6 + character.code - 'A'.code))
        }
        ?.joinToString("")
        ?: ""

internal val contactCountryCallingCodes = listOf(
    ContactCountryCallingCode("Afghanistan", "AF", "+93"),
    ContactCountryCallingCode("Albania", "AL", "+355"),
    ContactCountryCallingCode("Algeria", "DZ", "+213"),
    ContactCountryCallingCode("American Samoa", "AS", "+1"),
    ContactCountryCallingCode("Andorra", "AD", "+376"),
    ContactCountryCallingCode("Angola", "AO", "+244"),
    ContactCountryCallingCode("Anguilla", "AI", "+1"),
    ContactCountryCallingCode("Antigua and Barbuda", "AG", "+1"),
    ContactCountryCallingCode("Argentina", "AR", "+54"),
    ContactCountryCallingCode("Armenia", "AM", "+374"),
    ContactCountryCallingCode("Aruba", "AW", "+297"),
    ContactCountryCallingCode("Australia", "AU", "+61"),
    ContactCountryCallingCode("Austria", "AT", "+43"),
    ContactCountryCallingCode("Azerbaijan", "AZ", "+994"),
    ContactCountryCallingCode("Bahamas", "BS", "+1"),
    ContactCountryCallingCode("Bahrain", "BH", "+973"),
    ContactCountryCallingCode("Bangladesh", "BD", "+880"),
    ContactCountryCallingCode("Barbados", "BB", "+1"),
    ContactCountryCallingCode("Belarus", "BY", "+375"),
    ContactCountryCallingCode("Belgium", "BE", "+32"),
    ContactCountryCallingCode("Belize", "BZ", "+501"),
    ContactCountryCallingCode("Benin", "BJ", "+229"),
    ContactCountryCallingCode("Bermuda", "BM", "+1"),
    ContactCountryCallingCode("Bhutan", "BT", "+975"),
    ContactCountryCallingCode("Bolivia", "BO", "+591"),
    ContactCountryCallingCode("Bosnia and Herzegovina", "BA", "+387"),
    ContactCountryCallingCode("Botswana", "BW", "+267"),
    ContactCountryCallingCode("Brazil", "BR", "+55"),
    ContactCountryCallingCode("British Virgin Islands", "VG", "+1"),
    ContactCountryCallingCode("Brunei", "BN", "+673"),
    ContactCountryCallingCode("Bulgaria", "BG", "+359"),
    ContactCountryCallingCode("Burkina Faso", "BF", "+226"),
    ContactCountryCallingCode("Cambodia", "KH", "+855"),
    ContactCountryCallingCode("Cameroon", "CM", "+237"),
    ContactCountryCallingCode("Canada", "CA", "+1"),
    ContactCountryCallingCode("Cape Verde", "CV", "+238"),
    ContactCountryCallingCode("Cayman Islands", "KY", "+1"),
    ContactCountryCallingCode("Central African Republic", "CF", "+236"),
    ContactCountryCallingCode("Chad", "TD", "+235"),
    ContactCountryCallingCode("Chile", "CL", "+56"),
    ContactCountryCallingCode("China", "CN", "+86"),
    ContactCountryCallingCode("Colombia", "CO", "+57"),
    ContactCountryCallingCode("Comoros", "KM", "+269"),
    ContactCountryCallingCode("Congo", "CG", "+242"),
    ContactCountryCallingCode("Costa Rica", "CR", "+506"),
    ContactCountryCallingCode("Croatia", "HR", "+385"),
    ContactCountryCallingCode("Cuba", "CU", "+53"),
    ContactCountryCallingCode("Cyprus", "CY", "+357"),
    ContactCountryCallingCode("Czechia", "CZ", "+420"),
    ContactCountryCallingCode("Denmark", "DK", "+45"),
    ContactCountryCallingCode("Djibouti", "DJ", "+253"),
    ContactCountryCallingCode("Dominica", "DM", "+1"),
    ContactCountryCallingCode("Dominican Republic", "DO", "+1"),
    ContactCountryCallingCode("Ecuador", "EC", "+593"),
    ContactCountryCallingCode("Egypt", "EG", "+20"),
    ContactCountryCallingCode("El Salvador", "SV", "+503"),
    ContactCountryCallingCode("Equatorial Guinea", "GQ", "+240"),
    ContactCountryCallingCode("Eritrea", "ER", "+291"),
    ContactCountryCallingCode("Estonia", "EE", "+372"),
    ContactCountryCallingCode("Eswatini", "SZ", "+268"),
    ContactCountryCallingCode("Ethiopia", "ET", "+251"),
    ContactCountryCallingCode("Fiji", "FJ", "+679"),
    ContactCountryCallingCode("Finland", "FI", "+358"),
    ContactCountryCallingCode("France", "FR", "+33"),
    ContactCountryCallingCode("French Guiana", "GF", "+594"),
    ContactCountryCallingCode("French Polynesia", "PF", "+689"),
    ContactCountryCallingCode("Gabon", "GA", "+241"),
    ContactCountryCallingCode("Gambia", "GM", "+220"),
    ContactCountryCallingCode("Georgia", "GE", "+995"),
    ContactCountryCallingCode("Germany", "DE", "+49"),
    ContactCountryCallingCode("Ghana", "GH", "+233"),
    ContactCountryCallingCode("Gibraltar", "GI", "+350"),
    ContactCountryCallingCode("Greece", "GR", "+30"),
    ContactCountryCallingCode("Greenland", "GL", "+299"),
    ContactCountryCallingCode("Grenada", "GD", "+1"),
    ContactCountryCallingCode("Guadeloupe", "GP", "+590"),
    ContactCountryCallingCode("Guam", "GU", "+1"),
    ContactCountryCallingCode("Guatemala", "GT", "+502"),
    ContactCountryCallingCode("Guernsey", "GG", "+44"),
    ContactCountryCallingCode("Guinea", "GN", "+224"),
    ContactCountryCallingCode("Guinea-Bissau", "GW", "+245"),
    ContactCountryCallingCode("Guyana", "GY", "+592"),
    ContactCountryCallingCode("Haiti", "HT", "+509"),
    ContactCountryCallingCode("Honduras", "HN", "+504"),
    ContactCountryCallingCode("Hong Kong", "HK", "+852"),
    ContactCountryCallingCode("Hungary", "HU", "+36"),
    ContactCountryCallingCode("Iceland", "IS", "+354"),
    ContactCountryCallingCode("India", "IN", "+91"),
    ContactCountryCallingCode("Indonesia", "ID", "+62"),
    ContactCountryCallingCode("Iran", "IR", "+98"),
    ContactCountryCallingCode("Iraq", "IQ", "+964"),
    ContactCountryCallingCode("Ireland", "IE", "+353"),
    ContactCountryCallingCode("Isle of Man", "IM", "+44"),
    ContactCountryCallingCode("Israel", "IL", "+972"),
    ContactCountryCallingCode("Italy", "IT", "+39"),
    ContactCountryCallingCode("Jamaica", "JM", "+1"),
    ContactCountryCallingCode("Japan", "JP", "+81"),
    ContactCountryCallingCode("Jersey", "JE", "+44"),
    ContactCountryCallingCode("Jordan", "JO", "+962"),
    ContactCountryCallingCode("Kazakhstan", "KZ", "+7"),
    ContactCountryCallingCode("Kenya", "KE", "+254"),
    ContactCountryCallingCode("Kiribati", "KI", "+686"),
    ContactCountryCallingCode("Kosovo", "XK", "+383"),
    ContactCountryCallingCode("Kuwait", "KW", "+965"),
    ContactCountryCallingCode("Kyrgyzstan", "KG", "+996"),
    ContactCountryCallingCode("Laos", "LA", "+856"),
    ContactCountryCallingCode("Latvia", "LV", "+371"),
    ContactCountryCallingCode("Lebanon", "LB", "+961"),
    ContactCountryCallingCode("Lesotho", "LS", "+266"),
    ContactCountryCallingCode("Liberia", "LR", "+231"),
    ContactCountryCallingCode("Libya", "LY", "+218"),
    ContactCountryCallingCode("Liechtenstein", "LI", "+423"),
    ContactCountryCallingCode("Lithuania", "LT", "+370"),
    ContactCountryCallingCode("Luxembourg", "LU", "+352"),
    ContactCountryCallingCode("Macau", "MO", "+853"),
    ContactCountryCallingCode("Madagascar", "MG", "+261"),
    ContactCountryCallingCode("Malawi", "MW", "+265"),
    ContactCountryCallingCode("Malaysia", "MY", "+60"),
    ContactCountryCallingCode("Maldives", "MV", "+960"),
    ContactCountryCallingCode("Mali", "ML", "+223"),
    ContactCountryCallingCode("Malta", "MT", "+356"),
    ContactCountryCallingCode("Marshall Islands", "MH", "+692"),
    ContactCountryCallingCode("Martinique", "MQ", "+596"),
    ContactCountryCallingCode("Mauritania", "MR", "+222"),
    ContactCountryCallingCode("Mauritius", "MU", "+230"),
    ContactCountryCallingCode("Mayotte", "YT", "+262"),
    ContactCountryCallingCode("Mexico", "MX", "+52"),
    ContactCountryCallingCode("Micronesia", "FM", "+691"),
    ContactCountryCallingCode("Moldova", "MD", "+373"),
    ContactCountryCallingCode("Monaco", "MC", "+377"),
    ContactCountryCallingCode("Mongolia", "MN", "+976"),
    ContactCountryCallingCode("Montenegro", "ME", "+382"),
    ContactCountryCallingCode("Montserrat", "MS", "+1"),
    ContactCountryCallingCode("Morocco", "MA", "+212"),
    ContactCountryCallingCode("Mozambique", "MZ", "+258"),
    ContactCountryCallingCode("Myanmar", "MM", "+95"),
    ContactCountryCallingCode("Namibia", "NA", "+264"),
    ContactCountryCallingCode("Nauru", "NR", "+674"),
    ContactCountryCallingCode("Nepal", "NP", "+977"),
    ContactCountryCallingCode("Netherlands", "NL", "+31"),
    ContactCountryCallingCode("New Caledonia", "NC", "+687"),
    ContactCountryCallingCode("New Zealand", "NZ", "+64"),
    ContactCountryCallingCode("Nicaragua", "NI", "+505"),
    ContactCountryCallingCode("Niger", "NE", "+227"),
    ContactCountryCallingCode("Nigeria", "NG", "+234"),
    ContactCountryCallingCode("Niue", "NU", "+683"),
    ContactCountryCallingCode("North Korea", "KP", "+850"),
    ContactCountryCallingCode("North Macedonia", "MK", "+389"),
    ContactCountryCallingCode("Northern Mariana Islands", "MP", "+1"),
    ContactCountryCallingCode("Norway", "NO", "+47"),
    ContactCountryCallingCode("Oman", "OM", "+968"),
    ContactCountryCallingCode("Pakistan", "PK", "+92"),
    ContactCountryCallingCode("Palau", "PW", "+680"),
    ContactCountryCallingCode("Palestine", "PS", "+970"),
    ContactCountryCallingCode("Panama", "PA", "+507"),
    ContactCountryCallingCode("Papua New Guinea", "PG", "+675"),
    ContactCountryCallingCode("Paraguay", "PY", "+595"),
    ContactCountryCallingCode("Peru", "PE", "+51"),
    ContactCountryCallingCode("Philippines", "PH", "+63"),
    ContactCountryCallingCode("Poland", "PL", "+48"),
    ContactCountryCallingCode("Portugal", "PT", "+351"),
    ContactCountryCallingCode("Puerto Rico", "PR", "+1"),
    ContactCountryCallingCode("Qatar", "QA", "+974"),
    ContactCountryCallingCode("Reunion", "RE", "+262"),
    ContactCountryCallingCode("Romania", "RO", "+40"),
    ContactCountryCallingCode("Russia", "RU", "+7"),
    ContactCountryCallingCode("Rwanda", "RW", "+250"),
    ContactCountryCallingCode("Saint Kitts and Nevis", "KN", "+1"),
    ContactCountryCallingCode("Saint Lucia", "LC", "+1"),
    ContactCountryCallingCode("Saint Vincent and the Grenadines", "VC", "+1"),
    ContactCountryCallingCode("Samoa", "WS", "+685"),
    ContactCountryCallingCode("San Marino", "SM", "+378"),
    ContactCountryCallingCode("Sao Tome and Principe", "ST", "+239"),
    ContactCountryCallingCode("Saudi Arabia", "SA", "+966"),
    ContactCountryCallingCode("Senegal", "SN", "+221"),
    ContactCountryCallingCode("Serbia", "RS", "+381"),
    ContactCountryCallingCode("Seychelles", "SC", "+248"),
    ContactCountryCallingCode("Sierra Leone", "SL", "+232"),
    ContactCountryCallingCode("Singapore", "SG", "+65"),
    ContactCountryCallingCode("Slovakia", "SK", "+421"),
    ContactCountryCallingCode("Slovenia", "SI", "+386"),
    ContactCountryCallingCode("Solomon Islands", "SB", "+677"),
    ContactCountryCallingCode("Somalia", "SO", "+252"),
    ContactCountryCallingCode("South Africa", "ZA", "+27"),
    ContactCountryCallingCode("South Korea", "KR", "+82"),
    ContactCountryCallingCode("South Sudan", "SS", "+211"),
    ContactCountryCallingCode("Spain", "ES", "+34"),
    ContactCountryCallingCode("Sri Lanka", "LK", "+94"),
    ContactCountryCallingCode("Sudan", "SD", "+249"),
    ContactCountryCallingCode("Suriname", "SR", "+597"),
    ContactCountryCallingCode("Sweden", "SE", "+46"),
    ContactCountryCallingCode("Switzerland", "CH", "+41"),
    ContactCountryCallingCode("Syria", "SY", "+963"),
    ContactCountryCallingCode("Taiwan", "TW", "+886"),
    ContactCountryCallingCode("Tajikistan", "TJ", "+992"),
    ContactCountryCallingCode("Tanzania", "TZ", "+255"),
    ContactCountryCallingCode("Thailand", "TH", "+66"),
    ContactCountryCallingCode("Timor-Leste", "TL", "+670"),
    ContactCountryCallingCode("Togo", "TG", "+228"),
    ContactCountryCallingCode("Tonga", "TO", "+676"),
    ContactCountryCallingCode("Trinidad and Tobago", "TT", "+1"),
    ContactCountryCallingCode("Tunisia", "TN", "+216"),
    ContactCountryCallingCode("Turkey", "TR", "+90"),
    ContactCountryCallingCode("Turkmenistan", "TM", "+993"),
    ContactCountryCallingCode("Turks and Caicos Islands", "TC", "+1"),
    ContactCountryCallingCode("Tuvalu", "TV", "+688"),
    ContactCountryCallingCode("Uganda", "UG", "+256"),
    ContactCountryCallingCode("Ukraine", "UA", "+380"),
    ContactCountryCallingCode("United Arab Emirates", "AE", "+971"),
    ContactCountryCallingCode("United Kingdom", "GB", "+44"),
    ContactCountryCallingCode("United States", "US", "+1"),
    ContactCountryCallingCode("Uruguay", "UY", "+598"),
    ContactCountryCallingCode("Uzbekistan", "UZ", "+998"),
    ContactCountryCallingCode("Vanuatu", "VU", "+678"),
    ContactCountryCallingCode("Vatican City", "VA", "+39"),
    ContactCountryCallingCode("Venezuela", "VE", "+58"),
    ContactCountryCallingCode("Vietnam", "VN", "+84"),
    ContactCountryCallingCode("Wallis and Futuna", "WF", "+681"),
    ContactCountryCallingCode("Yemen", "YE", "+967"),
    ContactCountryCallingCode("Zambia", "ZM", "+260"),
    ContactCountryCallingCode("Zimbabwe", "ZW", "+263")
)

internal val defaultContactCountryCallingCode: ContactCountryCallingCode =
    contactCountryCallingCodes.first { it.countryCode == "IN" }

internal fun isValidLocalContactPhone(phone: String): Boolean =
    phone.isNotEmpty() && phone.all { it in '0'..'9' }

internal fun digitsOnlyLocalContactPhoneInput(value: String): String =
    value.filter { it in '0'..'9' }

internal fun isValidContactPhoneForSubmission(phone: String): Boolean =
    phone.isBlank() ||
        isValidContactPhone(phone) ||
        phone.matches(Regex("^\\+[0-9]+$"))

internal fun internationalContactPhone(
    country: ContactCountryCallingCode,
    localNumber: String
): String = country.callingCode + localNumber
